# Generated by Django 3.2.4 on 2021-06-10 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.phase'),
        ),
    ]
