# Generated by Django 3.2.4 on 2021-06-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_phase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-pk']},
        ),
        migrations.CreateModel(
            name='Challege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='tasks.task')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
